### ISSUE TITLE
no sound

### ISSUE THREAD

**Issue by logemann** [PonnamKarthik/FlutterYoutube#55]
on latest iOS when running the examples, i dont get any sound. Apart from that, the useFullscreen is also not working.

**Comment by jonatadashi** [comment]
Check if you have your iPhone in Silent Mode, that fixed it for me.

**Comment by TejaDroid** [comment]
me also facing same issue in iPhone

**Comment by JSWilProf** [comment]
Me too!
Flutter 1.17.5 • channel stable 
Dart 2.8.4
Xcode: 11.5.1
Swift: 5.2.4
iOS: 13.5.1
macOS: 10.15.5

**Comment by ponnamkarthik** [comment]
Hello @logemann @TejaDroid @JSWilProf Please use my new plugin which supports youtube for inline

[ext_video_player](https://pub.dartlang.org/packages/ext_video_player)

Thanks

**Comment by shadyshrif** [comment]
I had the same issue and I figured out the video was silent because the phone was in mute mode. I just added a note for users to unmute their phones to be able to hear video audio. I'm considering migration to ext_video_player but I just wanted to add the comment to tell you the reason that caused the issue
